#!/bin/bash

# Copies a file passed as an arg into the one running container
# This will fail if there is more than one container running
# podman cp bookmarks-2025-12-08.json firefox:/home/kasm-user

# Check if the number of arguments is zero
if [ "$#" -eq 0 ]; then
    echo "Error: No arguments provided, this requrires the file to copy into the container" >&2
    echo "Usage: $0 <argument>" >&2
    exit 1
fi

# Check if the file passed in as an argument exists
if [ -f "$1" ]; then
    echo "$1 exists and is a regular file."
else
    echo "$1 does not exist or is not a regular file."
fi


CONTAINER=$(podman ps --format "{{.Names}}")

echo $CONTAINER
#Copy the file in to the container


# This is not tested yet, this one block is generated by github copilot, so it may not work as expected, 
# but the idea is that if there is more than one container running it will ask the user which one to copy 
# the file into, if there is only one container running it will just copy the file into that container without asking
if [ $(echo "$CONTAINER" | wc -l) -gt 1 ]; then
    echo "Multiple containers found, please select one to copy the file into:"
    select CONTAINER in $CONTAINER; do
        if [ -n "$CONTAINER" ]; then
            break
        else
            echo "Invalid selection, please try again."
        fi
    done
fi  

# below here works fine
podman cp $1 $CONTAINER:/home/kasm-user

echo $1 copied in to the $CONTAINER container
