- name: Check disk space
  hosts: fedoraservervm
  tasks:
    - name: Show some Mount point and device info
      debug:
        msg: "{{ item.mount }} - {{ item.device }}"
      when: item.fstype == 'ext4'
      loop: "{{ ansible_facts.mounts }}"

