- name: Kevin Test 1
  hosts: Linux
  tasks:
  - name: Check to see that autofs is started
    ansible.builtin.service:
      name: autofs.service
      state: started
- name: Get size of /
  shell: "df --block-size 1m / --output=size | tail -1"
  register: shell_df_result

- name: Set facts
  set_fact:
    run_tmpfs_size_mb: "{{ shell_df_result.stdout | int }}"

- debug: var=root_tmpfs_size_mb
    #- name: Get size of /
    # shell: "df --block-size 1m / --output=size | tail -1"
    #  register: shell_df_result

    #- name: Set facts
    #  set_fact:
    #  root_tmpfs_size_mb: "{{ shell_df_result.stdout | int }}"

    #- debug: var=root_tmpfs_size_mb
