- name: Kevin Test 1
  hosts: Linux
  tasks:
  - name: Check to see that autofs is started
    ansible.builtin.service:
      name: autofs.service
      state: started
- name: Check Disk Space Usage
  hosts: Linux
  tasks:
          - name: Disk usage from command module
            command: df -h
            register: space
          - debug:
                  var: space