#
# Gathers facts for the machines in the Linux group (a.k.a Delegating facts)
# This works now, but doesn't return much -- kf
# - name: Gather info
#  hosts: Linux
#  tasks:
#    - name: Gather facts from server
#      ansible.builtin.setup:
#      delegate_to: "{{ item }}"
#      delegate_facts: true
#      loop: "{{ groups['Linux'] }}"
#
# This will work on hosts that use DNF/Yum generally fedora.
# Still need to put the files where they really belong, but it stages them in /backups/NFS for now

- name: Ansible Copy Example Local to Remote
  hosts: fedoraworkstation
  become: true
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /backups
        state: directory
        mode: '0755'
    - name: Install the latest version of NFS common package
      ansible.builtin.yum:
        name:
          - nfs-utils
          - autofs
    - name: Copy config files
      ansible.builtin.copy:
        src: /home/kevin/gitrepos/Linux-DesktopStuff/NFS
        dest: /backups
        owner: root
        group: root
        mode: 0644
        follow: true
    - name: Remove the Apache package
      ansible.builtin.yum:
        name: httpd
        state: absent
    - name: Create code directory
      ansible.builtin.file:
        path: /code
        state: directory
        owner: kevin
        group: kevin
        mode: 0775
    - name: Export /code
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: /code  *(rw,sync,no_subtree_check)
        state: present
    - name: Restart NFS server
      ansible.builtin.systemd:
        name: nfs-server.service
        state: reloaded
#    - name: Upgrade all packages
#      ansible.builtin.yum:
#        name: '*'
#        state: latest
#  Command to run this from Ansible server is     -->      ansible-playbook kmf2.yaml --extra-vars 'ansible_become_pass=PassWordHere

# The files in the directory are
# autofs.conf
# auto.master
# auto.nfs
# auto.smb
# nfs.conf
