# Ensure a service is started on all webservers:

# ansible webservers -m ansible.builtin.service -a "name=httpd state=started"
# Alternatively, restart a service on all webservers:

# ansible webservers -m ansible.builtin.service -a "name=httpd state=restarted"
# Ensure a service is stopped:

# ansible webservers -m ansible.builtin.service -a "name=httpd state=stopped"
# # ###################################################################################

#
# Gathers facts for the machines in the Linux group (a.k.a Delegating facts)
# This works now, but doesn't return much -- kf
# - name: Gather info
#  hosts: Linux
#  tasks:
#    - name: Gather facts from server
#      ansible.builtin.setup:
#      delegate_to: "{{ item }}"
#      delegate_facts: true
#      loop: "{{ groups['Linux'] }}"
- name: Do NFS setup
  hosts: pavillion
  tasks:

      # - name: Create a directory if it does not exist
      #  hosts: pavillion
      #  ansible.builtin.file:
      #    path: /backups
      #    state: directory
      #    mode: '0755'

      - name: Copy file with owner and permissions

        ansible.builtin.copy:
            src: ../Linux-DesktopStuff/NFS/autofs.conf
            dest: /backups/autofs.conf
            owner: root
            group: root
            mode: '644'

      - name: Copy file with owner and permissions
       
        ansible.builtin.copy:
            src: ../Linux-DesktopStuff/NFS/autofs.conf
            dest: /backups/autofs.conf
            owner: root
            group: root
            mode: '644'

      - name: Copy file with owner and permissions
        
        ansible.builtin.copy:
            src: ../Linux-DesktopStuff/NFS/auto.master
            dest: /backups/auto.master
            owner: root
            group: root
            mode: '644'

      - name: Copy file with owner and permissions
          
        ansible.builtin.copy:
            src: ../Linux-DesktopStuff/NFS/auto.nfs
            dest: /backups/auto.nfs
            owner: root
            group: root
            mode: '644'   

      - name: Copy file with owner and permissions
          
        ansible.builtin.copy:
            src: ../Linux-DesktopStuff/NFS/auto.smb
            dest: /backups/auto.smb
            owner: root
            group: root
            mode: '644'

      - name: Copy file with owner and permissions
         
        ansible.builtin.copy:
            src: ../Linux-DesktopStuff/NFS/nfs.conf
            dest: /backups/nfs.conf
            owner: root
            group: root
            mode: '644'

# autofs.conf  
# auto.master  
# auto.nfs  
# auto.smb  
# nfs.conf
