# Ensure a service is started on all webservers:

# ansible webservers -m ansible.builtin.service -a "name=httpd state=started"
# Alternatively, restart a service on all webservers:

# ansible webservers -m ansible.builtin.service -a "name=httpd state=restarted"
# Ensure a service is stopped:

# ansible webservers -m ansible.builtin.service -a "name=httpd state=stopped"
# # ###################################################################################

#
# Gathers facts for the machines in the Linux group (a.k.a Delegating facts)
# This works now, but doesn't return much -- kf
# - name: Gather info
#  hosts: Linux
#  tasks:
#    - name: Gather facts from server
#      ansible.builtin.setup:
#      delegate_to: "{{ item }}"
#      delegate_facts: true
#      loop: "{{ groups['Linux'] }}"
# - name: Do NFS setup
#  hosts: pavillion
#  tasks:

      # - name: Create a directory if it does not exist
      #  hosts: pavillion
      #  ansible.builtin.file:
      #    path: /backups
      #    state: directory
      #    mode: '0755'
# This will copy the whole directory, next is to copy the files from the directory
# to where they belog

- name: Ansible Copy Example Local to Remote
  hosts: fedoraworkstation
  become: true
  tasks:
    - name: Install the latest version of NFS common package
      ansible.builtin.yum:
        name: nfs-utils
    - name: Install autofs
      ansible.builtin.yum:
        name: autofs
    - name: Copy config files
      ansible.builtin.copy:
        src: /home/kevin/gitrepos/Linux-DesktopStuff/NFS
        dest: /backups
        owner: root
        group: root
        mode: 0644
        follow: true


#  Command to run this from Ansible server is     -->      ansible-playbook kmf2.yaml --extra-vars 'ansible_become_pass=PassWordHere

# The files in the directory are
# autofs.conf
# auto.master
# auto.nfs
# auto.smb
# nfs.conf
