- name: Hard disk test
  hosts: pavillion
#  connection: local
 # gather_facts: no
  vars:
    ism:
      host: pi
 #     username: "{{ username }}"
 #     password: "{{ password }}"

  tasks:

  - name: "Get hard disk information"
    inspur.ispim.hard_disk_info:
      provider: "{{ ism }}"
