# Ensure a service is started on all webservers:

# ansible webservers -m ansible.builtin.service -a "name=httpd state=started"
# Alternatively, restart a service on all webservers:

# ansible webservers -m ansible.builtin.service -a "name=httpd state=restarted"
# Ensure a service is stopped:

# ansible webservers -m ansible.builtin.service -a "name=httpd state=stopped"
# # ###################################################################################

#
# Gathers facts for the machines in the Linux group (a.k.a Delegating facts)
# This works now, but doesn't return much -- kf
# - name: Gather info
#  hosts: Linux
#  tasks:
#    - name: Gather facts from server
#      ansible.builtin.setup:
#      delegate_to: "{{ item }}"
#      delegate_facts: true
#      loop: "{{ groups['Linux'] }}"

- hosts: pavillion
#  connection: local
  vars:
    required_mounts:
      - '/' #present
 #     - '/fakemount' #missing
 #     - '/mnt/wsl/docker-desktop-data/version-pack-data' #present
  

  tasks: get info
    - set_fact:
        mount_names: "{{ ansible_mounts | map(attribute='mount') | list}}"
    - debug:
        var: mount_names
      loop: "{{ required_mounts }}"
      failed_when: item not in mount_names
