#
# Gathers facts for the machines in the Linux group (a.k.a Delegating facts)
# This works now, but doesn't return much -- kf
# - name: Gather info
#  hosts: Linux
#  tasks:
#    - name: Gather facts from server
#      ansible.builtin.setup:
#      delegate_to: "{{ item }}"
#      delegate_facts: true
#      loop: "{{ groups['Linux'] }}"
#
# This will work on hosts that use apt
# Still need to put the files where they really belong, but it stages them in /backups/NFS for now

- name: Ubuntu host config
  hosts: 
  become: true
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /backups
        state: directory
        mode: '0766'
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - nfs-common
          - nfs-kernel-server
          - autofs
        update_cache: true
    - name: Copy config files
      ansible.builtin.copy:
        src: /home/kevin/gitrepos/Linux-DesktopStuff/NFS
        dest: /backups
        owner: root
        group: root
        mode: 0644
        follow: true
    - name: Remove the Apache package
      ansible.builtin.apt:
        name: httpd
        state: absent
    - name: Create code directory
      ansible.builtin.file:
        path: /code
        state: directory
        owner: kevin
        group: kevin
        mode: 0775
    - name: Export /code
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: /code  *(rw,sync,no_subtree_check)
        state: present
    - name: Create code directory
      ansible.builtin.file:
        path: /nfs
        state: directory
        owner: kevin
        group: kevin
        mode: 0775
    - name: Update auto.master
      ansible.builtin.lineinfile:
        path: /etc/auto.master
        line: "/nfs /etc/auto.nfs"
        state: present
    - name: Auto.nfs
      ansible.builtin.lineinfile:
        path: /etc/auto.nfs
        line: pi -fstype=nfs4 pi:/media
        state: present
    - name: Insert lines in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.168.86.49 pavillion pavillion.flanagannc.net \n192.168.86.36 pi pi.flanagannc.net \n192.168.122.12 fedoraworkstation \n192.168.122.111 mint \n192.168.86.59 envy"
    - name: Restart NFS server
      ansible.builtin.systemd:
        name: nfs-server.service
        state: reloaded
#  Command to run this from Ansible server is     -->      ansible-playbook kmf2.yaml --extra-vars 'ansible_become_pass=PassWordHere

# The files in the directory are
# autofs.conf
# auto.master
# auto.nfs
# auto.smb
# nfs.conf
