- name: Apply all updates
  hosts: envy
  vars:
    # contents: "{{ lookup('file','c://temp/Winupdate_log.txt') }}"
  tasks:

    - name: Install all updates
      ansible.windows.win_updates:
        category_names: '*'
        reboot: false
        log_path: c:\temp\Winupdate_log.txt

# Above here works as expected
