
- name: Ansible apply updates to Fedora machines 
  hosts: fedorakde, fedoraws, CentOSStream, rocky9, almaliux, alma9, fedora,  awx
  become: true
  tasks:


###############  Update all packages
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:
