
- name: Ansible apply updates to Fedora machines 
  hosts: fedora
  # fedorakde, fedoraws, fedora, centosstream, rocky9, fedoraserver
  become: true
  tasks:


###############  Update all packages
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
