
- name: Ansible apply updates to Fedora machines 
  hosts: alma9, rocky9, fedoraserver, fedoraworkstation, fedora38
  become: true
  tasks:


###############  Update all packages
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
