- name: Kevin Test 1
  hosts: envy
  tasks:
  - name: Check to see that autofs is started
    ansible.builtin.service:
      name: autofs.service
      state: started
#  - name: size of memory
#    ansible_distribution


