- name: List to String Conversion
  hosts: localhost
  vars:
    my_list:
      - "apple"
      - "mango"
      - "orange"
  tasks:
    - name: Print the List
      debug:
        msg: "{{ my_list }}"

    - name: Concatenate a list to string
      set_fact:
        my_string: "{{ my_list | join(',') }}"

    - name: Print the String
      debug:
        msg: "{{ my_string }}"