---
- name: Look for code
  hosts: fedora
  become: true

  tasks:
    - name: Does code exist
      ansible.builtin.stat:
        path: "/tmp/code"
      register: register_name
    - name: Remove contents of directory
      ansible.builtin.file:
        path: /tmp/code/*
        state: absent
      when: register_name.stat.exists
...
