#
#
# This will work on hosts that use DNF/Yum generally fedora.
# Still need to put the files where they really belong, but it stages them in /backups/NFS for now
# Pre-requisites
# - /home/kevin/gitrepos/Linux-DesktopStuff/NFS must exist on the host running ansible,  Clone the Linux-DesktopStuff repo from github
# - /etc/hosts and /etc/ansible/hosts need to have the hosts in question configured there. 
# Limitations
# - Can see physical hosts on the network, or VMs on the same host as the one running the Ansible server

- name: Ansible configure Fedora machines for KF use
  hosts: alma9
  become: true
  tasks:
######  Install various file sharing packages if they aren't there
    - name: Install the latest version of NFS common package
      ansible.builtin.dnf:
        name:
          - nfs-utils
          - autofs
#############  Create a directory and Stash config files in it for if they are needed later
    - name: Create /backups directory if it does not exist
      ansible.builtin.file:
        path: /backups
        state: directory
        mode: '0755'
    - name: Copy config files to /backups/NFS
      ansible.builtin.copy:
        src: /home/kevin/gitrepos/Linux-DesktopStuff/NFS
        dest: /backups
        owner: root
        group: root
        mode: 0644
        follow: true
  #### Make sure that there's no Apache web server installed
    - name: Remove the Apache package
      ansible.builtin.dnf:
        name: httpd
        state: absent
##### Create directory for shared code
    - name: Create code directory
      ansible.builtin.file:
        path: /code
        state: directory
        owner: kevin
        group: kevin
        mode: 0775
#####  Update /etc/exports to Export /code and /media/nfs as NFS
    - name: Update /etc/exports
      ansible.builtin.lineinfile:
        path: /etc/exports
        state: present
        line: "{{ item }}"
      with_items:
        - '/media/nfs *(rw,no_root_squash)'
        - '/code  *(rw,sync,no_subtree_check)'
# Auto.nfs
    - name: Create auto.nfs file
      ansible.builtin.file:
        path: /etc/auto.nfs
        state: touch
        owner: root
        group: root
        mode: 0644
    - name: Update auto.nfs
      ansible.builtin.lineinfile:
        path: /etc/auto.nfs 
        line: '# Adding comment'
        line: envy -fstype=nfs4 192.168.1.104:/code
        state: present
################  Create /nfs
    - name: Create /nfs directory
      ansible.builtin.file:
        path: /nfs
        state: directory
        owner: kevin
        group: kevin
        mode: 0775
################  Create /misc
    - name: Create /misc directory
      ansible.builtin.file:
        path: /misc
        state: directory
        owner: kevin
        group: kevin
        mode: 0775
###################
# Auto.master
    - name: Create auto.master file
      ansible.builtin.file:
        path: /etc/auto.master
        state: touch
        owner: root
        group: root
        mode: 0644
    - name: Update auto.master
      ansible.builtin.lineinfile:
        path: /etc/auto.master
        state: present
        line: "{{ item }}"
      with_items:
        - '/misc   /etc/auto.misc'
        - '/nfs    /etc/auto.nfs'
############# Now that the NFS config is done, restart the server
    - name: Restart NFS server
      ansible.builtin.systemd:
        name: nfs-server.service
        state: reloaded
###############  Update all packages
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
#  Command to run this from Ansible server is     -->      ansible-playbook PlaybookName.yaml --extra-vars 'ansible_become_pass=PassWordHere
