- name: Check disk space
  hosts: fedorakde
  tasks:
    - name: Show filesystems
      debug:
#        msg: "{{ item.mount }} - {{ item.device }}"
        msg:  "{{ item.size_available }}"
# The when statement is a conditional, a bit like an if
# 
#      when: item.fstype == 'ext4'  
      when: item.fstype == 'autofs'
#      when: item.mount == '/boot'
#
# Here's the loop that walks through all of the mounts 
      loop: "{{ ansible_facts.mounts }}"
    