- name: Check disk space
  hosts: fedora38
  tasks:
    - name: Show filesystems that are ext4
      debug:
        msg: "{{ item.mount }} - {{ item.device }}"
      when: item.fstype == 'ext4'
      loop: "{{ ansible_facts.mounts }}"

