- name: Play with facts
  hosts: fedora
  tasks:
    - name: Show ip
      ansible.builtin.debug:
#        msg: "{{ item.mount }} - {{ item.device }}"
        msg: "{{ ansible_facts.default_ipv4.address }}"
#    - name: Print some facts
#      ansible.builtin.debug:
# This line will get all facts
#        var: ansible_facts
    - name: Print some facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Print Disk facts
      ansible.builtin.debug:
#        when: item.mount == '/'
        msg: "{{ ansible_facts.mounts }}"
    - name: Calculate disk free
      ansible.builtin.debug:
        msg: "{{ block_available * 4 /10 }}"
# This line will get all facts
#        var: ansible_facts
# See the facts for what you can get out
#        msg: "Current User: {{ ansible_facts.user_id }}"
#        msg: "Memory informaiton {{ ansible_facts.memory_mb }}"

#    - name: Facts about mounts
#      ansible.builtin.debug:
#        msg: "{{ ansible_facts.mounts }}"
#        msg: "{{ item.mount }} - {{ item.device }}"
# # The when statement is a conditional, a bit like an if
# #
#      when: item.fstype == 'ext4'
#      when: item.mount == '/boot'
#
# Here's the loop that walks through all of the mounts
#      loop: "{{ ansible_facts.XXXX }}"
# This is helpful for ideas as to what info is there
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html
